const assert = require('assert');
const os = require('os');
const path = require('path');
const esbuild = require('esbuild');

const out = path.join(os.tmpdir(), 'huginn-containers.test.js');
esbuild.buildSync({
  entryPoints: [path.join(__dirname, '..', 'src', 'marks', 'containers.ts')],
  outfile: out,
  bundle: true,
  format: 'cjs',
  platform: 'node',
  external: ['vscode'],
});

const {
  inspectMarkdown,
  cleanMarkdown,
  inspectHtml,
  cleanHtml,
  inspectSvg,
  cleanSvg,
} = require(out);

// Frontmatter: the AI keys go, the real ones stay, the body is untouched.
{
  const source = [
    '---',
    'title: Release notes',
    'generator: Claude',
    'tags:',
    '  - release',
    '---',
    '',
    '# Release notes',
    '',
    'generator: not frontmatter, just prose.',
    '',
  ].join('\n');

  const findings = inspectMarkdown(source);
  assert.strictEqual(findings.length, 1);
  assert.strictEqual(findings[0].confidence, 'probable');

  const { text, actions } = cleanMarkdown(source);
  assert.ok(!text.includes('generator: Claude'));
  assert.ok(text.includes('title: Release notes'));
  assert.ok(text.includes('  - release'));
  assert.ok(text.includes('generator: not frontmatter, just prose.'));
  assert.strictEqual(actions.length, 1);
}

// A dropped key takes its nested block with it.
{
  const source = ['---', 'provenance:', '  model: claude', '  date: 2026-01-01', 'title: Keep', '---', 'body', ''].join('\n');
  const { text } = cleanMarkdown(source);
  assert.ok(!text.includes('model: claude'));
  assert.ok(!text.includes('date: 2026-01-01'));
  assert.ok(text.includes('title: Keep'));
}

// Emptying the frontmatter removes the delimiters too.
{
  const { text, actions } = cleanMarkdown('---\ngenerator: Claude\n---\nbody\n');
  assert.strictEqual(text, 'body\n');
  assert.ok(actions.includes('removed empty frontmatter block'));
}

// No frontmatter, nothing to do.
{
  const source = '# Title\n\ngenerator: whatever\n';
  assert.deepStrictEqual(cleanMarkdown(source), { text: source, actions: [] });
  assert.deepStrictEqual(inspectMarkdown(source), []);
}

// HTML: AI meta and provenance JSON-LD go, viewport and CMS generator stay.
{
  const source = [
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width">',
    '<meta name="generator" content="WordPress 6.4">',
    '<meta name="generator" content="Claude">',
    '<script type="application/ld+json">{"digitalSourceType":"trainedAlgorithmicMedia"}</script>',
    '</head>',
    '<body><p data-ai-model="claude">hi</p></body>',
  ].join('\n');

  const findings = inspectHtml(source);
  const byConfidence = findings.map((f) => f.confidence);
  assert.ok(byConfidence.includes('informational'), 'CMS generator must stay informational');
  assert.ok(byConfidence.includes('confirmed'), 'parsed provenance must be confirmed');

  const { text, actions } = cleanHtml(source);
  assert.ok(text.includes('WordPress 6.4'), 'CMS generator must survive');
  assert.ok(text.includes('width=device-width'));
  assert.ok(text.includes('<meta charset="utf-8">'));
  assert.ok(!text.includes('content="Claude"'));
  assert.ok(!text.includes('trainedAlgorithmicMedia'));
  assert.ok(!text.includes('data-ai-model'));
  assert.ok(text.includes('<p>hi</p>'), 'the leading space goes with the attribute');
  assert.strictEqual(actions.length, 3);
}

// Clean HTML is a fixed point.
{
  const source = '<head><meta charset="utf-8"><title>x</title></head>';
  assert.deepStrictEqual(cleanHtml(source), { text: source, actions: [] });
  assert.deepStrictEqual(inspectHtml(source), []);
}

// SVG: metadata and XMP blocks go, the drawing stays.
{
  const source = [
    '<svg xmlns="http://www.w3.org/2000/svg">',
    '<metadata><rdf:RDF>c2pa</rdf:RDF></metadata>',
    '<x:xmpmeta><foo/></x:xmpmeta>',
    '<!-- generated by Claude -->',
    '<circle cx="5" cy="5" r="4"/>',
    '</svg>',
  ].join('\n');

  const findings = inspectSvg(source);
  assert.ok(findings.some((f) => f.confidence === 'informational'));
  assert.ok(findings.some((f) => f.confidence === 'probable'));

  const { text, actions } = cleanSvg(source);
  assert.ok(!text.includes('rdf:RDF'));
  assert.ok(!text.includes('xmpmeta'));
  assert.ok(!text.includes('generated by Claude'));
  assert.ok(text.includes('<circle cx="5" cy="5" r="4"/>'));
  assert.strictEqual(actions.length, 3);
}

// A plain SVG with no metadata is left alone.
{
  const source = '<svg xmlns="http://www.w3.org/2000/svg"><rect width="1" height="1"/></svg>';
  assert.deepStrictEqual(cleanSvg(source), { text: source, actions: [] });
  assert.deepStrictEqual(inspectSvg(source), []);
}

console.log('container tests passed');
