const assert = require('assert');
const os = require('os');
const path = require('path');
const esbuild = require('esbuild');

const out = path.join(os.tmpdir(), 'huginn-images.test.js');
esbuild.buildSync({
  entryPoints: [path.join(__dirname, '..', 'src', 'marks', 'images.ts')],
  outfile: out,
  bundle: true,
  format: 'cjs',
  platform: 'node',
  external: ['vscode'],
});

const {
  detectImageFormat,
  inspectPng,
  stripPng,
  inspectJpeg,
  stripJpeg,
  stripImage,
} = require(out);

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

// Kept chunks are copied byte for byte, so the CRC bytes here are never read.
function pngChunk(name, payload) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(payload.length);
  return Buffer.concat([length, Buffer.from(name, 'latin1'), payload, Buffer.from('CRC!')]);
}

function png(chunks) {
  return Buffer.concat([PNG_SIGNATURE, ...chunks]);
}

function jpegSegment(marker, payload) {
  const header = Buffer.alloc(4);
  header.writeUInt8(0xff, 0);
  header.writeUInt8(marker, 1);
  header.writeUInt16BE(payload.length + 2, 2);
  return Buffer.concat([header, payload]);
}

const IHDR = pngChunk('IHDR', Buffer.alloc(13, 1));
const IDAT = pngChunk('IDAT', Buffer.from('pixels'));
const IEND = pngChunk('IEND', Buffer.alloc(0));

{
  assert.strictEqual(detectImageFormat(png([IHDR, IEND])), 'png');
  assert.strictEqual(detectImageFormat(Buffer.from([0xff, 0xd8, 0xff, 0xe0])), 'jpeg');
  assert.strictEqual(detectImageFormat(Buffer.from('GIF89a')), 'unknown');
}

// PNG: text and EXIF chunks go, image data survives untouched.
{
  const source = png([
    IHDR,
    pngChunk('tEXt', Buffer.from('Software\0Claude')),
    pngChunk('eXIf', Buffer.from('exif payload')),
    IDAT,
    IEND,
  ]);

  const findings = inspectPng(source);
  assert.strictEqual(findings.length, 1);
  assert.ok(findings[0].message.includes('claude'));
  assert.strictEqual(findings[0].confidence, 'probable');

  const { data, actions } = stripPng(source);
  assert.strictEqual(actions.length, 2);
  assert.ok(data.equals(png([IHDR, IDAT, IEND])));
}

// A C2PA container chunk is a confirmed finding and gets dropped.
{
  const source = png([IHDR, pngChunk('caBX', Buffer.from('jumb')), IDAT, IEND]);
  const findings = inspectPng(source);
  assert.strictEqual(findings[0].confidence, 'confirmed');
  assert.ok(stripPng(source).data.equals(png([IHDR, IDAT, IEND])));
}

// Parsed provenance fields raise the confidence.
{
  const payload = Buffer.from('Description\0digitalSourceType=trainedAlgorithmicMedia');
  const findings = inspectPng(png([IHDR, pngChunk('iTXt', payload), IDAT, IEND]));
  assert.strictEqual(findings[0].confidence, 'confirmed');
}

// A PNG with nothing but structural chunks comes out identical.
{
  const source = png([IHDR, IDAT, IEND]);
  const { data, actions } = stripPng(source);
  assert.deepStrictEqual(actions, []);
  assert.ok(data.equals(source));
  assert.deepStrictEqual(inspectPng(source), []);
}

// JPEG: APP1/APP11 and COM go, JFIF and the entropy-coded scan survive.
{
  const jfif = jpegSegment(0xe0, Buffer.from('JFIF\0'));
  const scan = Buffer.concat([
    Buffer.from([0xff, 0xda, 0x00, 0x03, 0x01]),
    Buffer.from('entropy coded data'),
    Buffer.from([0xff, 0xd9]),
  ]);
  const source = Buffer.concat([
    Buffer.from([0xff, 0xd8]),
    jfif,
    jpegSegment(0xe1, Buffer.from('Exif\0\0Generated by Claude')),
    jpegSegment(0xeb, Buffer.from('jumb c2pa manifest')),
    jpegSegment(0xfe, Buffer.from('a comment')),
    scan,
  ]);

  const findings = inspectJpeg(source);
  assert.ok(findings.some((f) => f.message.includes('APP11') && f.confidence === 'confirmed'));
  assert.ok(findings.some((f) => f.message.includes('APP1:')));

  const { data, actions } = stripJpeg(source);
  assert.strictEqual(actions.length, 3);
  assert.ok(data.equals(Buffer.concat([Buffer.from([0xff, 0xd8]), jfif, scan])));
  assert.ok(data.includes(Buffer.from('entropy coded data')), 'the scan must survive');
  assert.ok(!data.includes(Buffer.from('Claude')));
}

// A JPEG with only JFIF comes out identical.
{
  const source = Buffer.concat([
    Buffer.from([0xff, 0xd8]),
    jpegSegment(0xe0, Buffer.from('JFIF\0')),
    Buffer.from([0xff, 0xda, 0x00, 0x03, 0x01]),
    Buffer.from('scan'),
    Buffer.from([0xff, 0xd9]),
  ]);
  const { data, actions } = stripJpeg(source);
  assert.deepStrictEqual(actions, []);
  assert.ok(data.equals(source));
}

// Anything that is not a PNG or a JPEG is refused, never rewritten blindly.
{
  assert.throws(() => stripImage(Buffer.from('GIF89a...')), /unsupported image format/);
}

console.log('image tests passed');
