import { Confidence, Finding } from './containers';

const PNG_SIGNATURE = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
const JPEG_SOI = Buffer.from([0xff, 0xd8]);

const C2PA_MARKERS = [
  'c2pa', 'jumb', 'c2ma', 'contentcredentials', 'contentauth', 'cai:',
];

const AI_META_HINTS = [
  'c2pa', 'contentcredentials', 'digitalsourcetype', 'trainedalgorithmicmedia',
  'compositewithtrainedalgorithmicmedia', 'algorithmicmedia', 'aigc',
  'ai generated', 'generated by', 'claude', 'anthropic', 'openai', 'synthid',
  'dcterms:provenance',
];

const CONFIRMED_MARKERS = [
  'digitalsourcetype', 'trainedalgorithmicmedia',
  'compositewithtrainedalgorithmicmedia', 'softwareagent',
];

export type ImageFormat = 'png' | 'jpeg' | 'unknown';

export function detectImageFormat(data: Buffer): ImageFormat {
  if (data.subarray(0, 8).equals(PNG_SIGNATURE)) return 'png';
  if (data.subarray(0, 2).equals(JPEG_SOI)) return 'jpeg';
  return 'unknown';
}

function markersIn(payload: Buffer, needles: string[]): string[] {
  const haystack = payload.toString('latin1').toLowerCase();
  return needles.filter((needle) => haystack.includes(needle));
}

function payloadConfidence(hits: string[]): Confidence {
  return hits.some((hit) => CONFIRMED_MARKERS.includes(hit)) ? 'confirmed' : 'probable';
}

const PNG_TEXT_CHUNKS = ['tEXt', 'zTXt', 'iTXt'];
const PNG_STRUCTURAL_CHUNKS = [
  'IHDR', 'IDAT', 'IEND', 'PLTE', 'tRNS', 'gAMA', 'pHYs', 'sRGB', 'cHRM', 'iCCP',
];

interface PngChunk {
  name: string;
  payload: Buffer;
  start: number;
  end: number;
}

function* pngChunks(data: Buffer): Generator<PngChunk> {
  let position = 8;
  while (position + 8 <= data.length) {
    const length = data.readUInt32BE(position);
    const name = data.toString('latin1', position + 4, position + 8);
    const payloadStart = position + 8;
    const payloadEnd = payloadStart + length;
    if (payloadEnd + 4 > data.length) return;

    yield {
      name,
      payload: data.subarray(payloadStart, payloadEnd),
      start: position,
      end: payloadEnd + 4,
    };

    if (name === 'IEND') return;
    position = payloadEnd + 4;
  }
}

function isC2paChunk(name: string): boolean {
  return name === 'caBX' || name === 'juMB' || name === 'jumb' || name.startsWith('c2');
}

export function inspectPng(data: Buffer): Finding[] {
  const findings: Finding[] = [];

  for (const chunk of pngChunks(data)) {
    if (isC2paChunk(chunk.name)) {
      findings.push({
        message: `PNG chunk ${chunk.name} (C2PA container)`,
        confidence: 'confirmed',
      });
    }
    if (PNG_TEXT_CHUNKS.includes(chunk.name) || chunk.name === 'eXIf') {
      const hits = markersIn(chunk.payload, [...AI_META_HINTS, ...C2PA_MARKERS]);
      if (hits.length > 0) {
        findings.push({
          message: `PNG ${chunk.name}: ${hits.slice(0, 8).join(', ')}`,
          confidence: payloadConfidence(hits),
        });
      }
    }
  }

  return findings;
}

export function stripPng(data: Buffer): { data: Buffer; actions: string[] } {
  const actions: string[] = [];
  const pieces: Buffer[] = [PNG_SIGNATURE];

  for (const chunk of pngChunks(data)) {
    const structural = PNG_STRUCTURAL_CHUNKS.includes(chunk.name);
    let drop = false;

    if (chunk.name === 'eXIf' || isC2paChunk(chunk.name)) {
      drop = true;
      actions.push(`drop chunk ${chunk.name}`);
    } else if (PNG_TEXT_CHUNKS.includes(chunk.name)) {
      drop = true;
      actions.push(`drop chunk ${chunk.name}`);
    } else if (!structural && markersIn(chunk.payload, C2PA_MARKERS).length > 0) {
      drop = true;
      actions.push(`drop chunk ${chunk.name} (C2PA marker in payload)`);
    }

    if (!drop) pieces.push(data.subarray(chunk.start, chunk.end));
  }

  return { data: Buffer.concat(pieces), actions };
}

const APP11 = 0xeb;
const APP0 = 0xe0;
const COM = 0xfe;
const SOS = 0xda;
const EOI = 0xd9;
const SOI = 0xd8;

interface JpegSegment {
  marker: number;
  payload: Buffer;
  start: number;
  end: number;
}

type JpegWalk = { segments: JpegSegment[]; scanStart: number };

function walkJpeg(data: Buffer): JpegWalk {
  const segments: JpegSegment[] = [];
  let i = 2;

  while (i + 4 <= data.length) {
    if (data[i] !== 0xff) {
      i++;
      continue;
    }
    while (i < data.length && data[i] === 0xff) i++;
    if (i >= data.length) break;

    const marker = data[i];
    const markerStart = i - 1;
    i++;

    if (marker === SOI || marker === EOI) continue;
    if (marker >= 0xd0 && marker <= 0xd7) continue;
    if (marker === SOS) return { segments, scanStart: markerStart };
    if (i + 2 > data.length) break;

    const length = data.readUInt16BE(i);
    if (length < 2 || i + length > data.length) break;

    segments.push({
      marker,
      payload: data.subarray(i + 2, i + length),
      start: markerStart,
      end: i + length,
    });
    i += length;
  }

  return { segments, scanStart: data.length };
}

function isAppSegment(marker: number): boolean {
  return marker >= 0xe0 && marker <= 0xef;
}

export function inspectJpeg(data: Buffer): Finding[] {
  const findings: Finding[] = [];

  for (const segment of walkJpeg(data).segments) {
    if (segment.marker === APP11) {
      findings.push({ message: 'JPEG APP11 segment (JUMBF/C2PA)', confidence: 'confirmed' });
    }
    if ([0xe1, 0xe2, 0xed, 0xee, APP11].includes(segment.marker)) {
      const hits = markersIn(segment.payload, [...AI_META_HINTS, ...C2PA_MARKERS]);
      if (hits.length > 0) {
        findings.push({
          message: `JPEG APP${segment.marker - APP0}: ${hits.slice(0, 8).join(', ')}`,
          confidence: payloadConfidence(hits),
        });
      }
    }
  }

  return findings;
}

export function stripJpeg(data: Buffer): { data: Buffer; actions: string[] } {
  const actions: string[] = [];
  const pieces: Buffer[] = [JPEG_SOI];
  const { segments, scanStart } = walkJpeg(data);

  for (const segment of segments) {
    let drop = false;

    if (segment.marker === APP11) {
      drop = true;
      actions.push('drop APP11 (C2PA/JUMBF)');
    } else if (isAppSegment(segment.marker) && segment.marker !== APP0) {
      drop = true;
      actions.push(`drop APP${segment.marker - APP0}`);
    } else if (segment.marker === COM) {
      drop = true;
      actions.push('drop COM comment');
    }

    if (!drop) pieces.push(data.subarray(segment.start, segment.end));
  }

  pieces.push(data.subarray(scanStart));
  return { data: Buffer.concat(pieces), actions };
}

export function inspectImage(data: Buffer): Finding[] {
  const format = detectImageFormat(data);
  if (format === 'png') return inspectPng(data);
  if (format === 'jpeg') return inspectJpeg(data);
  return [];
}

export function stripImage(data: Buffer): { data: Buffer; actions: string[] } {
  const format = detectImageFormat(data);
  if (format === 'png') return stripPng(data);
  if (format === 'jpeg') return stripJpeg(data);
  throw new Error(`unsupported image format: ${format}`);
}
